title: Shelley Engeneering Blog
description: Learn the latest and greatest about top industry engineering use cases & best practices :)

url: mariussnijder.github.io

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
